Add prefix to search and include searching for name and job fields
AY2122S2-CS2103T-T09-2/tp pull request #90
Opened 2022-03-17 04:27 UTC by kaiyichen

resolves #89 
- added name and job prefix to search
- able to search an applicant based on partial matching keywords of name or job

2022-03-18 15:08 UTC, RyanCheungJF reviewed
Tested on my own local machine and works well. Overall a great addition! There are some small stuff which could be changed to improve code quality.

2022-03-18 15:08 UTC, RyanCheungJF commented on src/main/java/seedu/linkedout/logic/parser/SearchCommandParser.java
> +        if (!anyPrefixesPresent(argMultimap, PREFIX_NAME, PREFIX_JOB)
This expression can be a bit over-complicated, if possible can split the 3 conditions into 3 different booleans with corresponding names. 

Written in pseudocode:

```suggestion
        boolean nameForCond1 = !anyPrefixes ...
        boolean nameForCond2 = !argMultimap...
        boolean nameForCond3 = !args.isEmpty()...
        if (cond1 || cond2 || cond3)
```

2022-03-18 15:08 UTC, RyanCheungJF commented on src/main/java/seedu/linkedout/logic/parser/SearchCommandParser.java
> +    private static boolean anyPrefixesPresent(ArgumentMultimap argumentMultimap, Prefix... prefixes) {
Would be good to add a javadoc comment describing the method!

2022-03-18 22:55 UTC, zzhikai reviewed
Great work on the search Command! Overall clean and well written code including the tests.

To be discussed during group meeting:

- Feasibility of combining the different prefix as some sort of search with filterS instead of just matching one prefix

Will review again and approve once @RyanCheungJF requested changes are done!

2022-03-18 22:55 UTC, zzhikai commented on src/main/java/seedu/linkedout/logic/commands/SearchCommand.java
> +            + PREFIX_JOB + "Job "
I was thinking whether we want to have the message be [n/Name] [j/Job] but still mention that at least one of it is compulsory for the search to work, as judging from this message, it means both prefixes are compulsory.

2022-03-19 12:12 UTC, zzhikai approved these changes
LGTM!

2022-03-20 10:59 UTC, RyanCheungJF requested changes
One minor last change, to keep the the naming of the booleans in line with the coding standards.

2022-03-20 10:59 UTC, RyanCheungJF commented on src/main/java/seedu/linkedout/logic/parser/SearchCommandParser.java
> +        boolean noPrefixesPresent = !anyPrefixesPresent(argMultimap, PREFIX_NAME, PREFIX_JOB);
Apologies for requesting another change but would be good to rename in accordance to coding standards:
(Same for the other booleans used)

![image](https://user-images.githubusercontent.com/63341400/159159051-e48b5094-6c11-4f52-a16a-76c70e345540.png)


```suggestion
        boolean hasNoPrefixesPresent = !anyPrefixesPresent(argMultimap, PREFIX_NAME, PREFIX_JOB);
```

2022-03-20 12:19 UTC, RyanCheungJF approved these changes

2022-03-20 12:19 UTC, merged