Update DeveloperGuide with UML diagrams and proposed flag feature
AY2122S2-CS2103T-T09-2/tp pull request #97
Opened 2022-03-23 08:29 UTC by ryantanlien

- Updates the remaining UML diagrams that have not yet been updated by Ryan C's PR
-  Added the text section for proposed flag feature (Will elaborate more with UML diagrams in a later PR)

2022-03-23 08:59 UTC, RyanCheungJF reviewed
Small changes, but other than that LGTM!

2022-03-23 08:59 UTC, RyanCheungJF commented on docs/diagrams/BetterModelClassDiagram.puml
> +AddressBook *-right-> "1" UniqueApplicantList
```suggestion
Linkedout *-right-> "1" UniqueApplicantList
```

2022-03-23 08:59 UTC, RyanCheungJF commented on docs/DeveloperGuide.md
> +`Applicants` will also be edited to contain a boolean `flagged` for use as a comparator in the `ObservablePriorityQueue`
```suggestion
`Applicant` will also be edited to contain a boolean `flagged` for use as a comparator in the `ObservablePriorityQueue`
```

2022-03-24 02:02 UTC, RyanCheungJF requested changes
My apologies, but need to generate the pictures and update them as well.

2022-03-24 08:20 UTC, ryantanlien commented
Done with sorting the merge conflicts!

2022-03-24 08:27 UTC, kaiyichen approved these changes
LGTM!!

2022-03-24 08:31 UTC, RyanCheungJF approved these changes

2022-03-24 08:31 UTC, merged